package com.company.test;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class SkuImage implements Serializable {

    private Integer branchId;
    private Integer posId;
    private String imgXmlUrl;
    private String skuNames;
    private Integer imageSources;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.tenant_id
     *
     * @mbg.generated
     */
    private Integer tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.source_type
     *
     * @mbg.generated
     */
    private Byte sourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.is_marked
     *
     * @mbg.generated
     */
    private Boolean isMarked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.marked_type
     *
     * @mbg.generated
     */
    private Byte markedType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.marked_date
     *
     * @mbg.generated
     */
    private Date markedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.order_num
     *
     * @mbg.generated
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.is_checked
     *
     * @mbg.generated
     */
    private Boolean isChecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.xml_url
     *
     * @mbg.generated
     */
    private String xmlUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.is_delete
     *
     * @mbg.generated
     */
    private Boolean isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.img_height
     *
     * @mbg.generated
     */
    private Integer imgHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.img_width
     *
     * @mbg.generated
     */
    private Integer imgWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sku_image.xml_content
     *
     * @mbg.generated
     */
    private String xmlContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sku_image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_image
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SkuImage other = (SkuImage) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
                && (this.getTenantId() == null ? other.getTenantId() == null : this.getTenantId().equals(other.getTenantId()))
                && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
                && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
                && (this.getSourceType() == null ? other.getSourceType() == null : this.getSourceType().equals(other.getSourceType()))
                && (this.getIsMarked() == null ? other.getIsMarked() == null : this.getIsMarked().equals(other.getIsMarked()))
                && (this.getMarkedType() == null ? other.getMarkedType() == null : this.getMarkedType().equals(other.getMarkedType()))
                && (this.getMarkedDate() == null ? other.getMarkedDate() == null : this.getMarkedDate().equals(other.getMarkedDate()))
                && (this.getOrderNum() == null ? other.getOrderNum() == null : this.getOrderNum().equals(other.getOrderNum()))
                && (this.getIsChecked() == null ? other.getIsChecked() == null : this.getIsChecked().equals(other.getIsChecked()))
                && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
                && (this.getXmlUrl() == null ? other.getXmlUrl() == null : this.getXmlUrl().equals(other.getXmlUrl()))
                && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
                && (this.getGroupId() == null ? other.getGroupId() == null : this.getGroupId().equals(other.getGroupId()))
                && (this.getImgHeight() == null ? other.getImgHeight() == null : this.getImgHeight().equals(other.getImgHeight()))
                && (this.getImgWidth() == null ? other.getImgWidth() == null : this.getImgWidth().equals(other.getImgWidth()))
                && (this.getXmlContent() == null ? other.getXmlContent() == null : this.getXmlContent().equals(other.getXmlContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_image
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getTenantId() == null) ? 0 : getTenantId().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getSourceType() == null) ? 0 : getSourceType().hashCode());
        result = prime * result + ((getIsMarked() == null) ? 0 : getIsMarked().hashCode());
        result = prime * result + ((getMarkedType() == null) ? 0 : getMarkedType().hashCode());
        result = prime * result + ((getMarkedDate() == null) ? 0 : getMarkedDate().hashCode());
        result = prime * result + ((getOrderNum() == null) ? 0 : getOrderNum().hashCode());
        result = prime * result + ((getIsChecked() == null) ? 0 : getIsChecked().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getXmlUrl() == null) ? 0 : getXmlUrl().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getGroupId() == null) ? 0 : getGroupId().hashCode());
        result = prime * result + ((getImgHeight() == null) ? 0 : getImgHeight().hashCode());
        result = prime * result + ((getImgWidth() == null) ? 0 : getImgWidth().hashCode());
        result = prime * result + ((getXmlContent() == null) ? 0 : getXmlContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sku_image
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", tenantId=").append(tenantId);
        sb.append(", createDate=").append(createDate);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", sourceType=").append(sourceType);
        sb.append(", isMarked=").append(isMarked);
        sb.append(", markedType=").append(markedType);
        sb.append(", markedDate=").append(markedDate);
        sb.append(", orderNum=").append(orderNum);
        sb.append(", isChecked=").append(isChecked);
        sb.append(", url=").append(url);
        sb.append(", xmlUrl=").append(xmlUrl);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", groupId=").append(groupId);
        sb.append(", imgHeight=").append(imgHeight);
        sb.append(", imgWidth=").append(imgWidth);
        sb.append(", xmlContent=").append(xmlContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
